services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/var/www/
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy
          
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/
      - ./docker/nginx/:/etc/nginx/conf.d/
    networks:
      - laravel
    depends_on:
      db:
        condition: service_healthy
          
  db:
    container_name: db
    image: mysql:8.0
    platform: linux/x86_64
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: finanza
    ports:
      - "3306:3306"
    networks:
      - laravel
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 1s
      timeout: 5s
      retries: 55
            
networks:
  laravel:
    driver: bridge